import { Article } from "./types";

export const SEED_ARTICLES: Article[] = [
  {
    id: "a1",
    slug: "world-leaders-gather-for-emergency-climate-summit-in-accra",
    title: "World Leaders Gather for Emergency Climate Summit in Accra",
    excerpt:
      "Heads of state from more than 40 nations arrive in Ghana's capital as scientists warn the window to limit warming is closing faster than projected.",
    body: "Delegations from more than 40 countries began arriving in Accra on Monday for an emergency climate summit convened after new data showed global temperatures rising faster than any major model had projected.\n\nThe three-day summit, hosted at the Accra International Conference Centre, is expected to produce a binding framework on emissions from shipping and aviation — two sectors that have long escaped international regulation.\n\n\"We are past the era of pledges. This is the era of enforcement,\" the summit's secretary-general told reporters on the tarmac. Security has been tightened across the capital, with major roads around the conference district closed to traffic.\n\nAnalysts say the presence of the world's three largest emitters at the same negotiating table for the first time in four years is itself a breakthrough, regardless of the final communiqué.",
    category: "world",
    author: "Kwame Mensah",
    tags: ["climate", "summit", "accra", "diplomacy"],
    status: "published",
    isBreaking: true,
    isFeatured: true,
    views: 12840,
    publishedAt: "2026-07-06T08:30:00.000Z",
    updatedAt: "2026-07-06T08:30:00.000Z",
  },
  {
    id: "a2",
    slug: "markets-rally-as-central-bank-signals-first-rate-cut-in-two-years",
    title: "Markets Rally as Central Bank Signals First Rate Cut in Two Years",
    excerpt:
      "Stocks surged to record highs after policymakers hinted that borrowing costs could fall as early as September.",
    body: "Global markets rallied sharply on Tuesday after the central bank's policy committee signalled it was prepared to deliver its first interest rate cut in two years, citing cooling inflation and a resilient labour market.\n\nThe benchmark index closed up 2.4 percent, its best single-day performance since January, while bond yields fell across the curve.\n\n\"The committee judges that the balance of risks has shifted,\" the bank said in its statement, language that traders immediately read as the clearest signal yet of easing to come.\n\nEconomists cautioned that a September cut is not guaranteed. Two more inflation prints are due before the committee meets again, and any upside surprise could push the timeline back into the new year.",
    category: "business",
    author: "Abena Osei",
    tags: ["markets", "interest rates", "economy"],
    status: "published",
    isBreaking: true,
    isFeatured: false,
    views: 9310,
    publishedAt: "2026-07-06T14:10:00.000Z",
    updatedAt: "2026-07-06T14:10:00.000Z",
  },
  {
    id: "a3",
    slug: "parliament-passes-landmark-digital-rights-bill-after-marathon-debate",
    title: "Parliament Passes Landmark Digital Rights Bill After Marathon Debate",
    excerpt:
      "The sweeping legislation guarantees citizens the right to access, correct and delete personal data held by companies and the state.",
    body: "Parliament passed the long-awaited Digital Rights and Data Protection Bill late Thursday night, capping a marathon 14-hour sitting that saw more than 120 amendments debated.\n\nThe law, which takes effect in January, gives citizens the legal right to access, correct and delete personal data held by both private companies and government agencies, and establishes an independent Data Commission with powers to levy fines of up to 4 percent of annual turnover.\n\nOpposition lawmakers, who had pushed for stronger protections against state surveillance, ultimately backed the bill after securing a judicial warrant requirement for any government access to private communications.\n\nCivil society groups welcomed the vote as \"a generational win,\" though several warned that enforcement will depend on how quickly the new commission is funded and staffed.",
    category: "politics",
    author: "Efua Boateng",
    tags: ["parliament", "data protection", "legislation"],
    status: "published",
    isBreaking: false,
    isFeatured: true,
    views: 7205,
    publishedAt: "2026-07-05T21:45:00.000Z",
    updatedAt: "2026-07-05T21:45:00.000Z",
  },
  {
    id: "a4",
    slug: "quantum-chip-breakthrough-puts-error-free-computing-within-reach",
    title: "Quantum Chip Breakthrough Puts Error-Free Computing Within Reach",
    excerpt:
      "Researchers demonstrate a logical qubit that runs a thousand times longer than previous designs, a milestone the field has chased for a decade.",
    body: "A research team announced Wednesday that it has built a logical qubit capable of sustaining error-corrected operations a thousand times longer than any previous design — a milestone quantum physicists have pursued for over a decade.\n\nThe chip, fabricated on a standard silicon process, chains together 49 physical qubits into a single fault-tolerant unit that corrected its own errors in real time during a 12-hour continuous run.\n\n\"This is the moment the field stops being about physics experiments and starts being about engineering,\" said one senior researcher involved in the work.\n\nPractical machines capable of breaking current encryption or simulating new materials remain years away, the team stressed, but the result removes what many considered the single biggest obstacle on the roadmap.",
    category: "technology",
    author: "Yaw Darko",
    tags: ["quantum computing", "research", "silicon"],
    status: "published",
    isBreaking: false,
    isFeatured: true,
    views: 11020,
    publishedAt: "2026-07-05T09:15:00.000Z",
    updatedAt: "2026-07-05T09:15:00.000Z",
  },
  {
    id: "a5",
    slug: "black-stars-stun-brazil-in-world-cup-quarter-final-thriller",
    title: "Black Stars Stun Brazil in World Cup Quarter-Final Thriller",
    excerpt:
      "A 94th-minute winner sends Ghana into the semi-finals for the first time in the nation's history, sparking celebrations across the country.",
    body: "Ghana's Black Stars produced the shock of the tournament on Saturday, beating Brazil 2-1 with a 94th-minute winner to reach the World Cup semi-finals for the first time in the nation's history.\n\nThe stadium erupted when the striker rose above two defenders to head home a corner deep into stoppage time, moments after Brazil thought they had done enough to force extra time.\n\nBack home, streets from Accra to Tamale filled within minutes of the final whistle. The government declared Monday a public holiday.\n\n\"We told the boys before kick-off: nobody remembers the team that almost made history,\" the head coach said. Ghana will face the winner of Sunday's tie between France and Argentina.",
    category: "sports",
    author: "Kofi Asante",
    tags: ["world cup", "black stars", "football", "ghana"],
    status: "published",
    isBreaking: true,
    isFeatured: false,
    views: 25400,
    publishedAt: "2026-07-04T19:55:00.000Z",
    updatedAt: "2026-07-04T19:55:00.000Z",
  },
  {
    id: "a6",
    slug: "who-approves-first-single-dose-malaria-vaccine-for-adults",
    title: "WHO Approves First Single-Dose Malaria Vaccine for Adults",
    excerpt:
      "Health officials call the approval a turning point in the fight against a disease that still kills more than 600,000 people every year.",
    body: "The World Health Organization on Friday approved the first single-dose malaria vaccine for adults, a decision health officials described as a turning point in the fight against a disease that kills more than 600,000 people every year.\n\nIn late-stage trials across twelve countries, the vaccine reduced severe malaria cases by 81 percent over two years — far exceeding the efficacy of earlier multi-dose regimens that proved difficult to complete in rural areas.\n\nManufacturing partners say they can produce 200 million doses a year at full capacity, with the first shipments scheduled for early 2027.\n\n\"A single visit, a single jab, two years of protection — that changes what is operationally possible,\" said one immunization program director.",
    category: "health",
    author: "Dr. Ama Serwaa",
    tags: ["malaria", "vaccine", "who", "public health"],
    status: "published",
    isBreaking: false,
    isFeatured: false,
    views: 8650,
    publishedAt: "2026-07-04T11:20:00.000Z",
    updatedAt: "2026-07-04T11:20:00.000Z",
  },
  {
    id: "a7",
    slug: "streaming-wars-heat-up-as-rivals-merge-into-entertainment-giant",
    title: "Streaming Wars Heat Up as Rivals Merge Into Entertainment Giant",
    excerpt:
      "The $84 billion deal creates the world's second-largest streaming service and is expected to face intense regulatory scrutiny.",
    body: "Two of the world's biggest streaming platforms announced an $84 billion merger on Monday, creating the second-largest subscription video service on the planet and reshaping an industry that has been locked in a costly battle for subscribers.\n\nThe combined company will serve roughly 310 million households and control one of the deepest content libraries ever assembled, spanning film, prestige television, live sport and gaming.\n\nRegulators in three jurisdictions signalled they would examine the deal closely, with consumer groups warning it could accelerate price rises that have already tested subscriber patience.\n\nExecutives defended the merger as survival economics. \"Scale is no longer a strategy choice in streaming — it is the price of admission,\" the incoming chief executive told investors.",
    category: "entertainment",
    author: "Nana Adjoa",
    tags: ["streaming", "merger", "media"],
    status: "published",
    isBreaking: false,
    isFeatured: false,
    views: 5980,
    publishedAt: "2026-07-03T16:40:00.000Z",
    updatedAt: "2026-07-03T16:40:00.000Z",
  },
  {
    id: "a8",
    slug: "west-african-single-currency-clears-final-hurdle-launch-set-for-2027",
    title: "West African Single Currency Clears Final Hurdle, Launch Set for 2027",
    excerpt:
      "Finance ministers ratify the eco framework after fifteen years of negotiation, setting the stage for the region's biggest monetary shift in generations.",
    body: "Finance ministers from the West African monetary zone ratified the final framework for the eco single currency on Wednesday, clearing the last institutional hurdle after fifteen years of stop-start negotiation.\n\nThe currency will launch in January 2027 across six countries in the first phase, with a common central bank headquartered in Abuja and convergence criteria on inflation, deficits and reserves.\n\nEconomists are divided on the timeline. Supporters argue a common currency will slash cross-border transaction costs that currently eat up to 7 percent of regional trade value. Skeptics point to the eurozone's early crises as a warning about unifying currencies before fiscal policy.\n\nMarkets reacted calmly, with regional bonds broadly unchanged — a sign, one analyst said, \"that investors have finally started believing the project is real.\"",
    category: "world",
    author: "Kwame Mensah",
    tags: ["eco", "currency", "ecowas", "economy"],
    status: "published",
    isBreaking: false,
    isFeatured: false,
    views: 6420,
    publishedAt: "2026-07-03T07:55:00.000Z",
    updatedAt: "2026-07-03T07:55:00.000Z",
  },
  {
    id: "a9",
    slug: "ai-tutors-roll-out-to-ten-thousand-public-schools-in-national-pilot",
    title: "AI Tutors Roll Out to Ten Thousand Public Schools in National Pilot",
    excerpt:
      "The education ministry says the adaptive learning program will reach four million students by the end of the school year.",
    body: "The education ministry began rolling out AI-powered tutoring software to ten thousand public schools on Monday, the largest deployment of adaptive learning technology in the region's history.\n\nThe system, which runs on low-cost tablets and works offline in areas with poor connectivity, adjusts lesson difficulty in real time and flags struggling students to teachers before they fall behind.\n\nIn a two-year pilot across 300 schools, students using the tutor for forty minutes a day improved math scores by the equivalent of an extra 1.3 years of schooling.\n\nTeacher unions cautiously welcomed the program while insisting it must supplement, not replace, classroom staff. \"The tablet does not manage a classroom of fifty children. The teacher does,\" the union's general secretary said.",
    category: "technology",
    author: "Yaw Darko",
    tags: ["ai", "education", "schools"],
    status: "published",
    isBreaking: false,
    isFeatured: false,
    views: 4875,
    publishedAt: "2026-07-02T13:05:00.000Z",
    updatedAt: "2026-07-02T13:05:00.000Z",
  },
  {
    id: "a10",
    slug: "opposition-names-surprise-candidate-ahead-of-december-election",
    title: "Opposition Names Surprise Candidate Ahead of December Election",
    excerpt:
      "The 43-year-old former central banker emerges from a bruising primary as the youngest presidential nominee in the party's history.",
    body: "The main opposition party named a 43-year-old former central bank deputy governor as its presidential candidate on Sunday, a surprise result that makes her the youngest nominee in the party's history.\n\nShe defeated two party heavyweights in a primary that ran to a third ballot, drawing her strongest support from delegates under forty and from the party's urban strongholds.\n\nHer acceptance speech leaned heavily on economic themes — jobs, the cost of living, and what she called \"a decade of borrowed growth\" — while avoiding direct attacks on the incumbent.\n\nPolitical analysts said the choice signals a generational bet. \"The party has decided the path to victory runs through young urban voters who feel unrepresented by both establishments,\" one Accra-based pollster said. The election is scheduled for December 7.",
    category: "politics",
    author: "Efua Boateng",
    tags: ["election", "opposition", "candidate"],
    status: "published",
    isBreaking: false,
    isFeatured: false,
    views: 9840,
    publishedAt: "2026-07-02T06:45:00.000Z",
    updatedAt: "2026-07-02T06:45:00.000Z",
  },
  {
    id: "a11",
    slug: "cocoa-prices-hit-record-as-farmers-demand-bigger-share",
    title: "Cocoa Prices Hit Record as Farmers Demand Bigger Share",
    excerpt:
      "Futures touch an all-time high while producer nations push chocolate makers to accept a new floor price mechanism.",
    body: "Cocoa futures touched an all-time high on Thursday as the world's two largest producers pressed chocolate manufacturers to accept a new floor price mechanism designed to guarantee farmers a living income.\n\nThe producing nations, which together grow more than 60 percent of the world's cocoa, have threatened to withhold forward sales from buyers who refuse the premium.\n\nFor decades, farmers have captured barely 6 percent of the value of a chocolate bar. The new mechanism would add a fixed living-income differential of $400 per tonne on every contract.\n\nMajor confectioners have so far split in their response — two global brands signed on within days, while others are lobbying for a phased introduction. \"The era of cheap cocoa built on poor farmers is ending,\" the regulator's chief executive said.",
    category: "business",
    author: "Abena Osei",
    tags: ["cocoa", "commodities", "farmers", "trade"],
    status: "published",
    isBreaking: false,
    isFeatured: false,
    views: 5210,
    publishedAt: "2026-07-01T10:30:00.000Z",
    updatedAt: "2026-07-01T10:30:00.000Z",
  },
  {
    id: "a12",
    slug: "afrobeats-star-announces-record-breaking-world-stadium-tour",
    title: "Afrobeats Star Announces Record-Breaking World Stadium Tour",
    excerpt:
      "The 40-date tour will be the largest ever headlined by an African artist, with stops on five continents.",
    body: "One of Afrobeats' biggest global stars announced a 40-date world stadium tour on Tuesday, the largest ever headlined by an African artist, with stops across five continents beginning in March 2027.\n\nThe tour opens with back-to-back nights at Accra's Independence Square before moving through London, Paris, New York, São Paulo, Johannesburg and Tokyo.\n\nPre-registration for tickets crashed the promoter's website within an hour of the announcement, with more than four million sign-ups recorded on the first day.\n\nIndustry watchers called the tour a milestone for the genre's commercial power. \"Ten years ago the question was whether Afrobeats could fill arenas abroad. Now it is filling stadiums on every continent,\" one music executive said.",
    category: "entertainment",
    author: "Nana Adjoa",
    tags: ["afrobeats", "music", "tour"],
    status: "published",
    isBreaking: false,
    isFeatured: false,
    views: 7730,
    publishedAt: "2026-06-30T18:15:00.000Z",
    updatedAt: "2026-06-30T18:15:00.000Z",
  },
  {
    id: "a13",
    slug: "new-study-links-daily-walking-to-sharply-lower-dementia-risk",
    title: "New Study Links Daily Walking to Sharply Lower Dementia Risk",
    excerpt:
      "Researchers tracking 78,000 adults for a decade found that 7,000 steps a day cut dementia risk by nearly half.",
    body: "Adults who walked at least 7,000 steps a day were 48 percent less likely to develop dementia over the following decade, according to one of the largest studies of physical activity and brain health ever conducted.\n\nResearchers tracked 78,000 adults aged 45 to 75 using wrist-worn sensors, then followed their health records for ten years — an approach far more reliable than the self-reported questionnaires used in earlier work.\n\nThe protective effect appeared at surprisingly modest intensity. Brisk pace helped, but total daily volume mattered most, and benefits plateaued around 10,000 steps.\n\n\"This is the strongest evidence yet that the cheapest intervention we have — walking — meaningfully protects the ageing brain,\" the study's lead author said.",
    category: "health",
    author: "Dr. Ama Serwaa",
    tags: ["dementia", "exercise", "research"],
    status: "published",
    isBreaking: false,
    isFeatured: false,
    views: 6115,
    publishedAt: "2026-06-30T08:00:00.000Z",
    updatedAt: "2026-06-30T08:00:00.000Z",
  },
  {
    id: "a14",
    slug: "draft-investigation-stadium-financing",
    title: "Investigation: Who Really Paid for the National Stadium?",
    excerpt:
      "A six-month investigation into the financing behind the new national stadium raises questions about undisclosed loans.",
    body: "This is a working draft of the stadium financing investigation. Key documents are still being verified with two independent sources before publication.\n\nOutstanding items: confirm the loan agreement dates, obtain comment from the ministry, and finalize the graphics package.",
    category: "sports",
    author: "Kofi Asante",
    tags: ["investigation", "stadium"],
    status: "draft",
    isBreaking: false,
    isFeatured: false,
    views: 0,
    publishedAt: "2026-07-06T15:00:00.000Z",
    updatedAt: "2026-07-06T15:00:00.000Z",
  },
];
